### ISSUE TITLE
Does this handle 429 TOO MANY REQUESTS?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [twolfson/pinboard.js#1]
I'd like to comply with Pinboard's API requirements, but I don't want to write backing-off code manually. Could that be integrated here?

**Comment by twolfson** [comment]
I would prefer to keep this library focused on making requests only -- one thing well. There are backoff libraries available in `npm` that you should be able to use for this:

https://github.com/MathieuTurcotte/node-backoff

That being said, it's better to pace yourself and know you are going to hit a request limit than get slapped by the server =/
