### ISSUE TITLE
Caching feature for handling rate limits of pinboard.in service

### ISSUE THREAD

**Issue by jpalala** [twolfson/pinboard.js#2]
I think that the pinboard plugin which uses pinboard.js works even without a rate limiter by redirecting user to the actual page (all bookmarks - go to pinboard.in/:your username).

However it would be nice to add some kind of simple caching feature that would check for last timestamp (via a simple file?) of request and check if last posts/all call was 5 minutes ago or not).

More info on rate limited pinboard.in API at https://pinboard.in/api/

> API requests are limited to one call per user every three seconds, except for the following:
> 
> posts/all - once every five minutes
> posts/recent - once every minute

**Comment by twolfson** [comment]
Caching can be implemented in a lot of ways (e.g. LRU, caching in memory, caching to disk). It's best for us to keep this library low level and if anyone wants to implement caching on top of it, then they can wrap with their needs.
